### ISSUE TITLE
Missing Help/About...

### ISSUE THREAD

**Issue by iakov** [lvjonok/maze-gui-gen#4]
Typical menu option with useful information
1. Program name and short description,
1. Version info.
1. Author/contributors/copyright
1. Licence

**Comment by lvjonok** [comment]
What should I mention in copyright and license?
I have added MIT license for my repository, but I don't really know is it good or bad.

**Comment by iakov** [comment]
Closed in https://github.com/lvjonok/maze-gui-gen/commit/00e31ff163547634332b9280f44fab18893bb8fb
