### ISSUE TITLE
Use some rationale design guidelines for the interface

### ISSUE THREAD

**Issue by iakov** [lvjonok/maze-gui-gen#5]
For example, this one can be used from [ElementaryOS](https://elementary.io/docs/human-interface-guidelines)
First, use \u2026 ellipses char (…)  for menus with further [action](https://elementary.io/docs/human-interface-guidelines#using-ellipses).

**Comment by lvjonok** [comment]
Changed design in last pushed version

**Comment by iakov** [comment]
Use text like "Fixes #5" for commit message to close issue automatically

**Comment by iakov** [comment]
Also I strongly advise to add features/fixes with PRs, and PRs can be used to close issues with "Closes/Fixes #issue_num"

**Comment by iakov** [comment]
Fixed in https://github.com/lvjonok/maze-gui-gen/commit/786348e137b527e2881e71de4bb44521606453f1 or a little bit later
